#!/bin/sh

# Generate a new change ID using the current commit hash and the committer email address
change_id="Change-Id: I$(git rev-parse HEAD | openssl sha1 | sed 's/^.* //')"

# Check if the commit message already contains a change ID
if ! grep -q "Change-Id:" "$1"; then
  # If not, add the generated change ID to the commit message
  echo "$change_id" >> "$1"
fi
