name: Update JSON

on:
    schedule:
        - cron: "0 0 * * Sun"
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    update_apps_list:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run PowerShell script
              shell: pwsh
              run: .github/scripts/script.ps1

            - name: Commit changes
              run: |
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config user.name "github-actions[bot]"
                  git add .
                  git commit -m "Update install_apps.json"
                  git push
